apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment #name of the deployment
  labels:
    app: nginx 
spec:
  replicas: 3 #Creates 3 of the same pods with this state 
  selector:
    matchLabels:
      app: nginx #This inidicates How the replicaset finds wich pods to manage
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
